### PR TITLE
Make Solid Rectangle crosssect folder compliant with crosssect guidelines

### PR DESCRIPTION
**Pull request by aimthiazz**
This PR makes the `solidRectangle` crosssect folder compliant with the crosssect guidelines.

### CODE REVIEW

**Review by ngadiyar93 — CHANGES_REQUESTED** [review]
@aimthiazz The labels look quite tiny in the rendered markdown.  Could you increase the font size of the labels / scale up the image? Otherwise, it looks good to me.

**Review by elsevers — CHANGES_REQUESTED** [review]
`Rectangle` is misspelled in the `readme.md` file.

**Review by Bharat-Ramadas — DISMISSED** [review]
Looks good

**Review by elsevers — CHANGES_REQUESTED** [review]
1. The class name is not consistent with the folder name and drawing names. (`CrossSectSolidRect ~= CrossSectSolidRectangle`). Please fix this. I prefer renaming `CrossSectSolidRect` to be `CrossSectSolidRectangle`. Making this update will require you to update the rest of the code base the utilizes this cross-section (probably just a couple examples).
2. The drawing is drawn unnecessarily large. Please try to match the style of the trapezoid drawing.

**Comment by aimthiazz** [comment]
1. Updated Class name from `CrossSectSolidRect` to `CrossSectSolidRectangle`  across the code base - checked code function by running `exampleLinearMotor.m` and `exampleSolidRectangle.m` 

2. Resized `CrossSectSolidRectangle.svg` to match `trapezoid.svg`.

**Review by Bharat-Ramadas — APPROVED** [review]
Look good

**Review by ngadiyar93 — APPROVED** [review]

**Review by elsevers — APPROVED** [review]
Looks good. Thanks @aimthiazz

**Pull request merged**
