### PR TITLE
Add flux barrier rotor cross section

### PR DESCRIPTION
**Pull request by Aneesh-Jategaonkar**
This PR adds the flux barrier rotor cross section drawing capability to the Python implementation of eMach. The example script corresponding to this cross-section is python/examples/example_flux_barrier_rotor.py

### CODE REVIEW

**Review by elsevers — CHANGES_REQUESTED** [review]
Thanks Aneesh. However, this PR seems to be missing the `README.md` file necessary to be compliant with eMach cross sections. The image of the cross-section also is not using the naming convention.

Please review eMach cross-section guidelines [here](https://github.com/Severson-Group/eMach/tree/develop/model_obj/crosssects).

**Review by Bharat-Ramadas — COMMENTED** [review]
The cross-section looks great! Nice job!
Would suggest the following changes:

1. Right now it seems that the number the flux barriers per pole is fixed at 3. It might be worthwhile to make this a variable as well.
2. Remove fillets in the cross-section figure as this is currently not implemented.

**Review by elsevers — CHANGES_REQUESTED** [review]
Looking good. I am confused about the dimensions `l_m1`, `l_m2`, `l_m3`. It seems to me that these dimensions are tied only to magnets and have nothing to do with the dimensions of the IPM rotor cross-section. Why are they needed for this class?

There are many types of IPM rotor cross-sections. Is there a more descriptive name that we can be using for this type of IPM rotor?

Does this class always need to have 3 magnets / bridge sections per pole? It looks like that is non-configurable (that's okay if it is), is that correct?

**Comment by elsevers** [comment]
> The cross-section looks great! Nice job! Would suggest the following changes:
> 
>     1. Right now it seems that the number the flux barriers per pole is fixed at 3. It might be worthwhile to make this a variable as well.
> 
>     2. Remove fillets in the cross-section figure as this is currently not implemented.

1. It would be wonderful if this was a variable.
2. Fillets are important! Please implement them.

**Comment by Aneesh-Jategaonkar** [comment]
> Looking good. I am confused about the dimensions `l_m1`, `l_m2`, `l_m3`. It seems to me that these dimensions are tied only to magnets and have nothing to do with the dimensions of the IPM rotor cross-section. Why are they needed for this class?
> 
> There are many types of IPM rotor cross-sections. Is there a more descriptive name that we can be using for this type of IPM rotor?
> 
> Does this class always need to have 3 magnets / bridge sections per pole? It looks like that is non-configurable (that's okay if it is), is that correct?

l_m1, l_m2 and l_m3 dimensions were deleted. They are not needed for this class. I have changed the name to Flux Barrier Rotor. The bridge sections per pole are presently non-configurable. Fillets are added.

**Review by Bharat-Ramadas — COMMENTED** [review]
Looking good. Only changes I would suggest is to switch from `P = number of poles` to `p = number of pole pairs`, for consistency with other cross-sections

**Comment by Aneesh-Jategaonkar** [comment]
> Looking good. Only changes I would suggest is to switch from `P = number of poles` to `p = number of pole pairs`, for consistency with other cross-sections

The change has been made and updated in the .svg file as well

**Review by Bharat-Ramadas — DISMISSED** [review]
Looks good!

**Review by elsevers — DISMISSED** [review]
Nice job @Aneesh-Jategaonkar

**Review by elsevers — APPROVED** [review]
Nice job @Aneesh-Jategaonkar

**Pull request merged**
