### PR TITLE
Create a model component "hollow cylinder"

### PR DESCRIPTION
**Pull request by Anvar-Khamitov**

### CODE REVIEW

**Comment by npetersen2** [comment]
Anvar, you include an axial length of the hollow cylinder, but this is not implemented in mn, as it is 2D.

Maybe we should separate 3D components from 2D? Seems a little confusing for this component to have dimensions that someone would have no plans of using for 2D models.

**Comment by elsevers** [comment]
Please add source file for PDF drawing. (svg)

**Comment by elsevers** [comment]
Please follow 80 char limit for code line length

**Comment by npetersen2** [comment]
Looks pretty good. For using XFEMM as the tool, it looks as if you have implemented the methods using the function interface like we were originally doing.

Can you change your implementation to create an `XFEMM.m` class which resembles the `MagNet.m` and `TikZ.m` class? You can follow the `MagNet` class as an example.

Then, update your example to match the `main.m` example, which creates the cross sections, puts them into a component, and then instantiates your new `XFEMM` class and uses it to draw your component.

**Comment by elsevers** [comment]
This appears to still have the file `tools/xfemm/model/xfemm_drawHollowCylinder.m`. Please address this, then merge develop into this branch, remove `dim_depth` and adjust for using the new `Location2d.transformCoords()`.

Let us know when you are ready for this to be merged.

**Comment by Anvar-Khamitov** [comment]
This PR is ready for review

**Review by elsevers — APPROVED** [review]
Looks good. Let's merge it.

**Review by npetersen2 — APPROVED** [review]
Looks good! Let's merge it!

**Pull request merged**
