### PR TITLE
Breadloaf

### PR DESCRIPTION
**Pull request by Nick-Hemenway**

### CODE REVIEW

**Comment by Nick-Hemenway** [comment]
The dimension drawing still needs to be finished

**Comment by elsevers** [comment]
@Nick-Hemenway Where are we at with this? Are you ready for us to review/comment?

**Comment by elsevers** [comment]
Please merge `develop` into this branch and adjust things to use your Location2D.transformCoords(). 

Let me know when this is complete and you are ready for me to merge this back into develop.

**Comment by elsevers** [comment]
Please move the local origin to a point on one of the cross-section edges.

**Comment by Nick-Hemenway** [comment]
I believe that the breadloaf cross section is ready to be merged into develop. I updated the coordinates as had been discussed (see the breadloaf drawing files). The example for extruding breadloaf works also. Please review this so that it can be merged.

**Comment by elsevers** [comment]
Fix inconsistency with dim_l vs dimension being labeled as L

**Review by npetersen2 — APPROVED** [review]
Looks good to me

**Pull request merged**
