### PR TITLE
Update hollow cylinder cross-section

### LINKED ISSUE #170: Make CrossSects folders match instructions
PR #168 and #177 add instructions for the expected contents of each CrossSects folder. We now need to make these folders have consistent content.

List of cross-sects to review (check off as completed):

- [x] `arc` (@ASHAD1 )
- [x] `breadloaf` (@Bharat-Ramadas )
- [x] `hollowCylinder` (@Bharat-Ramadas )
- [x] `hollowRectangle` (@ASHAD1 )
- [x] `innerNotchedRectangle` (@ngadiyar93)
- [x] `inner_rotor_stator` (@ngadiyar93 )
- [x] `linearMotorStator` (@ngadiyar93 )
- [x] `notchedRectangle` (@aimthiazz)
- [x] `outerRotor` (@aimthiazz)
- [x] `outerRotorStator` (@aimthiazz)
- [x] `parallelogram`
- [x] `solidRectangle`
- [x] `trapezoid` (@elsevers / @ngadiyar93)

**Please sign up for cross-sections that you are planning to review/revise**

### PR DESCRIPTION
**Pull request by Bharat-Ramadas**

### CODE REVIEW

**Review by ngadiyar93 — DISMISSED** [review]

**Review by aimthiazz — COMMENTED** [review]
1. I'm not sure whether the fonts are rendered properly.
image

2. Should the dimension arrow be black in color? (Ref. to Trapezoid cross sect)

**Comment by Bharat-Ramadas** [comment]
@aimthiazz  The .svg has a solid black font for `da`. I tried deleting the text and re-typing, but that didn't work.
The dimension indicators have been modified to be black in color.

**Review by aimthiazz — DISMISSED** [review]

**Review by ngadiyar93 — DISMISSED** [review]

**Review by elsevers — CHANGES_REQUESTED** [review]
Please use subscripts in the variable names. 

What does the `a` stand for in `d_a`? 

Are these variables bold-face? (if so, please remove the bold style)

The circle lines also look excessively thick compared other drawings, but this may be due to the SVG rendering in markdown

**Comment by Bharat-Ramadas** [comment]
`d_a` variable name updated to `t_c` to stand for thickness of cylinder. 
Text formatting modified and circle thickness reduced.

**Comment by elsevers** [comment]
How about just calling the thickness `t`?

**Comment by Bharat-Ramadas** [comment]
`t` works as well.

**Review by aimthiazz — APPROVED** [review]

**Review by elsevers — APPROVED** [review]
Looks good.

**Pull request merged**
