### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by elsevers**
Initial commit of BSD 3 license into project 

Following GitHub guidelines:

- Copyright listed as owner of GitHub account (Eric Severson)
- Current year (2019)

### CODE REVIEW

**Review by npetersen2 — CHANGES_REQUESTED** [review]
Looks like we need to list instructions on how to use GitHub Issues. I can write something for how I'd like to see them used, and then update the `CONTRIBUTING.md` file.

**Comment by npetersen2** [comment]
If my added instructions about using GitHub Issues are acceptable, I approve this PR.

**Review by npetersen2 — APPROVED** [review]

**Review by ngadiyar93 — APPROVED** [review]
Looks good to me

**Review by Anvar-Khamitov — APPROVED** [review]

**Review by Nick-Hemenway — APPROVED** [review]

**Comment by npetersen2** [comment]
@elsevers Can you also merge this into `develop` branch as people will be basing new topic branches from `develop`

**Comment by elsevers** [comment]
Yep, that's the plan. Looks like everyone has approved. I will start the process now.

**Pull request merged**
