### PR TITLE
Create trapezoid component

### PR DESCRIPTION
**Pull request by npetersen2**

### CODE REVIEW

**Comment by npetersen2** [comment]
Note that this not ready to merge, as the trapezoid drawing is a jpg and not a Latex svg file. I will update this soon.

**Comment by elsevers** [comment]
Please change length dimension to be height.

**Comment by elsevers** [comment]
Please add dimension for z height.

**Comment by npetersen2** [comment]
Ready to pull this trapezoid component into develop branch. Note that all this will be redone once new architecture is in place, but this PR conforms to the current system design.

@elsevers please review and accept this PR.

**Pull request merged**
