### PR TITLE
Make OuterRotor crosssect folder compliant with crosssect guidelines

### PR DESCRIPTION
**Pull request by aimthiazz**
This PR makes the `OuterRotor` crosssect folder compliant with the crosssect

### CODE REVIEW

**Review by Bharat-Ramadas — DISMISSED** [review]
Looks good

**Review by elsevers — CHANGES_REQUESTED** [review]
Please make font sizes consistent.

**Review by elsevers — CHANGES_REQUESTED** [review]
These font sizes are very different:
image

**Review by Bharat-Ramadas — DISMISSED** [review]
Looks good

**Review by elsevers — CHANGES_REQUESTED** [review]
Please make these variables lower case:
- [x] `p` for number of pole-pairs
- [x] `r_ro`

**Comment by aimthiazz** [comment]
Modified the variable names `R_ro` and `P` to `r_ro` and `p` in both svg and codebase. Checked the code by running `OuterRotorExample.m`.

**Review by elsevers — APPROVED** [review]

**Review by ngadiyar93 — APPROVED** [review]
Looks good to me

**Pull request merged**
