### PR TITLE
XFEMM class

### PR DESCRIPTION
**Pull request by Anvar-Khamitov**

### CODE REVIEW

**Comment by Anvar-Khamitov** [comment]
This PR is ready for review.

**Comment by elsevers** [comment]
Please add `tools/xfemm/INSTALL.md` that explains how to get XFEMM set up so that it can be used.

**Comment by horychen** [comment]
> Please add `tools/xfemm/INSTALL.md` that explains how to get XFEMM set up so that it can be used.

A quick starting point:
https://sourceforge.net/p/xfemm/discussion/general/thread/1e23fdea/

**Comment by Anvar-Khamitov** [comment]
This PR is ready for review.

**Review by ngadiyar93 — APPROVED** [review]

**Review by elsevers — APPROVED** [review]
Fantastic!  Let's merge this but note the need for documentation on this.

Please create an issue that requests a word document outlining how the "fix" to the XFEMM problem (removing nodes, segments, arcs, etc.)

**Pull request merged**
