### PR TITLE
Add division of two DimLinear operation for making a ratio

### PR DESCRIPTION
**Pull request by npetersen2**

### CODE REVIEW

**Comment by npetersen2** [comment]
Note that this probably allows a user to divide two different types.... `DimInch / DimMillimeter`... Is this okay? The code casts both to LHS and RHS to same type (i.e. `DimMillimeter`) for the division, so I think this is the expected behavior...

**Comment by npetersen2** [comment]
Update: I have added another unit test to show the above commented behavior (see last test). I am now confident that this is the expected behavior. Please approve this PR so I can merge to `develop`.

**Comment by elsevers** [comment]
If they can divide two different types, the units should be converted to a consistent unit base before the divide operation. So, the scalar output for:
``` 
mmInch = dimMillimeter(25.4);
Inch = dimInch(1);
b = mmInch/Inch;
```

The result should be `b = 1` (double)

**Comment by npetersen2** [comment]
@elsevers Yes, this is what happens. See the expected result for the last test case (this passes).

**Review by Nick-Hemenway — APPROVED** [review]

**Review by elsevers — APPROVED** [review]
I ran the tests and took a look around. Looks great.

**Pull request merged**
