### PR TITLE
Add example of creating a laminated solenoid

### PR DESCRIPTION
**Pull request by elsevers**
Anvar, this example is a matlab script of the geometry I'd like you to model to investigate the eddy currents in laminated steel

### CODE REVIEW

**Comment by elsevers** [comment]
**NOT ready** to be merged. Anvar and I will be working on this.

**Comment by elsevers** [comment]
@Anvar-Khamitov this example doesn't run on a computer where MagNet is missing the material model named `M-19 24 Ga non-zero conductivity` from their user models. 

Can you please fix this? This will involve asking MagNet to clone a default library material and modifying its conductivity.

@ngadiyar93 -- it seems that you must be dealing with this type of situation in your project and in @wchan29's [project](https://github.com/Severson-Group/anson_nsf_repo/). Can you support @Anvar-Khamitov on this?

**Comment by elsevers** [comment]
@Anvar-Khamitov in addition, could you provide a `README.md` markdown doc in this folder that explains this example? I would like to see an SVG file drawing included and a brief description of the problem being modeled and MATLAB svg files of expected results. This document can fairly brief.

**Comment by Anvar-Khamitov** [comment]
@elsevers I fixed the issue (created two functions - one for cloning the system material and another for setting the conductivity) and added the README.md.

**Review by Bharat-Ramadas — APPROVED** [review]
All added examples are functional

**Pull request merged**
