### PR TITLE
Update Hollow Rectangle Example with MakeSolid

### PR DESCRIPTION
**Pull request by ngadiyar93**

### CODE REVIEW

**Comment by ngadiyar93** [comment]
This PR is ready for review

**Comment by elsevers** [comment]
Calculation of inner coordinate is not correct. It needs to be within the surface. Please correct and let us know when you are ready for a new review.

**Comment by Nick-Hemenway** [comment]
Add conditional check to verify if hollow rectangle is actually hollow. If not, do not add internal lines or vertices

**Comment by ngadiyar93** [comment]
This PR is ready for review

**Review by npetersen2 — APPROVED** [review]
Looks good to me! (with some changes later)

**Pull request merged**
