### PR TITLE
Update Crossects to be compliant

### PR DESCRIPTION
**Pull request by ngadiyar93**
This PR updates the following CrossSects assigned to @ngadiyar93 to be compliant with the latest crosssect guidelines:

- CrossSectInnerNotchedRotor
- CrossSectInnerRotorStator
- CrossSectLinearMotorStator

### CODE REVIEW

**Review by Bharat-Ramadas — DISMISSED** [review]
Looks good

**Review by aimthiazz — DISMISSED** [review]

**Review by elsevers — CHANGES_REQUESTED** [review]
None of these cross section diagrams are properly using subscripts (please fix)

The linear machine `README.md` file misspells the linear

Inner rotor stator uses an different font size for `x` and `y` coordinates

Remember that subscripts which are abbreviations should not be italicized

**Comment by ngadiyar93** [comment]
@elsevers I have addressed your feedback. This PR can be reviewed.

1. All subscripts were created using the `subscript` feature in inkscape and they weren't simply smaller font size. I have checked that again and confirmed it is indeed the case.
2. Fixed the linear machine `README.md`
3. Fixed the coordinate font size in `Inner rotor stator`
4. Subscripts which are abbreviations are no longer italicized.

**Review by elsevers — CHANGES_REQUESTED** [review]
Thanks Nishanth. 

Looking better. `Inner Rotor Stator Cross Section` drawing still needs more work.
- [x] Some annotations have double-sided arrows, when they should not, i.e. `r_sf`
- [x] More spacing is needed around some label text, i.e. `d_sp`, `\alpha_so`, etc.
- [x] Some arrow sizes are much smaller than others. Please use a consistent size.

I have tried to indicate all of this on the drawing below.


image

**Comment by ngadiyar93** [comment]
@elsevers I have addressed these issues.. 
The markdown doc now seems to show that `r_si` is approximately touching the dimension lines. 
However, if the svg is opened in inkscape, this is how it appears:
image

**Review by elsevers — APPROVED** [review]
Looks good -- thanks @ngadiyar93

**Review by aimthiazz — APPROVED** [review]
Looks good :)

**Pull request merged**
