### PR TITLE
Make OuterRotorStator crosssect folder compliant with crosssect guidelines

### PR DESCRIPTION
**Pull request by aimthiazz**
This PR makes the `OuterRotorStator`crosssect folder compliant with the crosssect guidelines.

### CODE REVIEW

**Review by Bharat-Ramadas — DISMISSED** [review]
Looks good

**Review by elsevers — CHANGES_REQUESTED** [review]
Drawing needs revision:

- Variable letter should be italicized that they are not in the subscripts
- For some reason, a smaller font is used for `r_sb`, `r_sf`, and `r_st`. This font size should be the same as the other variable names

**Review by elsevers — APPROVED** [review]
Looks good, thanks @aimthiazz

**Review by ngadiyar93 — APPROVED** [review]
Looks good

**Pull request merged**
