### PR TITLE
Add parametrized geometry for linear motor stator and movers

### PR DESCRIPTION
**Pull request by Anvar-Khamitov**

### CODE REVIEW

**Comment by elsevers** [comment]
Looking good. Please remove `g` from your drawing.

**Comment by elsevers** [comment]
Add some comments in `CrossSectLinearMotorStator.m` explaining:

- where the innerCoordinate is near line 110
- what is going on throughout lines 70 - 100

**Comment by Anvar-Khamitov** [comment]
This PR is ready for review.

**Review by npetersen2 — APPROVED** [review]

**Review by ngadiyar93 — APPROVED** [review]
Looks Good

**Pull request merged**
