### PR TITLE
Hollow rectangle

### PR DESCRIPTION
**Pull request by ngadiyar93**

### CODE REVIEW

**Comment by npetersen2** [comment]
Nishanth, confused by your parameterization. Does this lock this component into a fixed square shape? What if a hollow rectangle is desired?

**Comment by elsevers** [comment]
In addition to @npetersen2 's comment, @ngadiyar93:

- perhaps it isn't clearly indicated on [the trello card](https://trello.com/c/qaTvNuZD), but we should be able to specify the thickness of each side of the rectangle.
- move the anchor for the coordinate system to the center of the drawing

**Comment by elsevers** [comment]
Actually, please leave anchor in same location as drawn.

**Comment by elsevers** [comment]
Please change code style:
-  80 char line limit
- align similar code across lines
- consider using short local variable names for cleaner code

**Comment by ngadiyar93** [comment]
@elsevers I have cleaned up the code and added feature to implement variable thickness. Also, made it a rectangle - different dimension variables for length and breadth.

**Comment by npetersen2** [comment]
Seems almost perfect! Only two comments:
- Because each cross section defines the `draw()` method, we don't need the `mn_drawHollowRect()` function.
- Please fix indentation in your `CrossSectHollowRect.m` file.

**Comment by elsevers** [comment]
Looking good. 

Please merge develop into this branch, then update to use @Nick-Hemenway's new `Location2D.transformCoords()` for your cross-section coordinates. 

Run your example to make sure it works. If everything is good, post back here and I'll merge your pull request.

**Comment by ngadiyar93** [comment]
@elsevers I have modified files and it works fine.

**Comment by elsevers** [comment]
Looks good, I am merging this. I am going to create a new issue to change your nomenclature:

- Change `l_o` to `w`
- Change `b_o` to `h`
- Change `t_1` through `t_4` numbering. Place `t_1` on right side and go counter-clockwise. That is: `t_2` on the top, `t_3` on left, etc.

(on drawings and in the source)

**Pull request merged**
