### PR TITLE
Make variable names MATLAB style compliant

### LINKED ISSUE #137: Make variable names compliant with MATLAB style guide
Eliminate the preceding `i` from these names:

https://github.com/Severson-Group/eMach/blob/a1f209d25dee4c8db9b9dae0ab14e819871a7c3e/tools/magnet/MagNet.m#L22

### PR DESCRIPTION
**Pull request by ngadiyar93**
This PR makes the variable names MATLAB style compliant by removing the preceding "i" to some variable names.

### CODE REVIEW

**Review by Bharat-Ramadas — APPROVED** [review]
Looks good

**Comment by ASHAD1** [comment]
Looks good!

**Review by ASHAD1 — APPROVED** [review]

**Review by aimthiazz — APPROVED** [review]
Looks good.

**Comment by ngadiyar93** [comment]
@aimthiazz @ASHAD1 @Bharat-Ramadas Although this is a minor PR, it can break the code if there is a bug introduced. 
Could you please check this branch out, run an existing eMach example, and approve the PR only if it runs fine?
Thanks!

**Review by Bharat-Ramadas — APPROVED** [review]
Examples work fine on my system.

**Review by elsevers — APPROVED** [review]

**Pull request merged**
